server:
  port: 8086

spring:
  cloud:
    gateway:
      routes:
        - id: category-service
          uri:
            lb://category-service
          predicates:
            - Path=/categoryservice/**
        - id: cart-service
          uri:
            lb://cart-service
          predicates:
            - Path=/cartservice/**
        - id: order-service
          uri:
            lb://order-service
          predicates:
            - Path=/orderservice/**
        - id: review-service
          uri:
            lb://review-service
          predicates:
            - Path=/reviewservice/**
        - id: user-service
          uri:
            lb://user-service
          predicates:
            - Path=/userservice/**
  application:
    name: api-gateway-service
