server:
  port: 8086

spring:
  cloud:
    gateway:
      routes:
        - id: category-service
          uri: http://localhost:8081/
          predicates:
            - Path=/categoryservice/**
        - id: cart-service
          uri: http://localhost:8082/
          predicates:
            - Path=/cartservice/**
        - id: order-service
          uri: http://localhost:8083/
          predicates:
            - Path=/orderservice/**
        - id: review-service
          uri: http://localhost:8084/
          predicates:
            - Path=/reviewservice/**
        - id: user-service
          uri: http://localhost:8085/
          predicates:
            - Path=/userservice/**
  application:
    name: api-gateway-service
